; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Avro Keyboard"
#define MyAppExeName "Avro Keyboard.exe"
#define MyAppVersion GetFileVersion("build\" + MyAppExeName)
#define MyAppPublisher "OmicronLab"
#define MyAppURL "https://www.omicronlab.com/"
#define HomeAppURL "https://www.omicronlab.com/avro-keyboard.html"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{E2703872-FEFB-4B04-B89D-0DA64713B943}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

DefaultDirName={commonpf32}\{#MyAppName}

; Start Menu group/folder name
DefaultGroupName={#MyAppName}

; Enables the "Select Start Menu Folder" wizard page during setup
DisableProgramGroupPage=no
AllowNoIcons=yes

UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
VersionInfoTextVersion={#MyAppVersion}

ChangesAssociations=yes
LicenseFile=LICENSE.txt
OutputDir=Output
OutputBaseFilename=Setup_AvroKeyboard
SetupIconFile=assets\icons\Avro.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "build\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "assets\autodict.dct"; DestDir: "{commonappdata}\Avro Keyboard"; Flags: ignoreversion
Source: "assets\Database.db3"; DestDir: "{commonappdata}\Avro Keyboard"; Flags: ignoreversion
Source: "assets\skins\*"; DestDir: "{commonappdata}\Avro Keyboard\Skin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "assets\keyboard-layouts\*"; DestDir: "{commonappdata}\Avro Keyboard\Keyboard Layouts"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "build\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "assets\docs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "assets\fonts\Kalpurush.ttf"; DestDir: "{autofonts}"; FontInstall: "Kalpurush"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "assets\fonts\Kalpurush ANSI.ttf"; DestDir: "{autofonts}"; FontInstall: "Kalpurush ANSI"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "assets\fonts\SiyamRupali.ttf"; DestDir: "{autofonts}"; FontInstall: "Siyam Rupali"; Flags: onlyifdoesntexist uninsneveruninstall
Source: "assets\fonts\Siyam Rupali ANSI.ttf"; DestDir: "{autofonts}"; FontInstall: "Siyam Rupali ANSI"; Flags: onlyifdoesntexist uninsneveruninstall

[Dirs]
Name: "{commonappdata}\Avro Keyboard"; Permissions: users-modify

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
; 1. Main application shortcut (outside the folder, directly in the Start Menu)
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

; 2. Shortcuts inside the "Avro Keyboard" group folder
Name: "{group}\Avro Keyboard on the Web"; Filename: "{#HomeAppURL}"
Name: "{group}\Avro Spell Checker"; Filename: "{app}\Avro Spell Checker.exe"
Name: "{group}\Configuring your system"; Filename: "{app}\Configuring_system.htm"
Name: "{group}\Layout Editor"; Filename: "{app}\Layout Editor.exe"
Name: "{group}\Skin Designer"; Filename: "{app}\Skin Designer.exe"

; 3. Desktop shortcut (optional, based on task selection)
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent