program kat_avroshield;

{ End-to-end KAT for the pure-Pascal .AvroShield runtime stack
  (uAvroShield.pas): bytecode parse + deobfuscate, and full container
  load (HMAC verify -> AES-GCM decrypt -> zlib -> bytecode -> deobfuscate).

  All vectors were generated by the AvroShield Python toolchain
  (avroenco\ on the same machine) with password 'demo-avroshield-password':
    kat_portable.AvroEnco  - flags 0x09 (password only, no machine bind)
    kat_bound.AvroEnco     - flags 0x0F (bound to this machine)
    kat_sample.bytecode      - raw AVROBC bytecode of the same layout JSON
  Expected JSON text is the exact output of json.dumps(ensure_ascii=False)
  from the Python engine. }

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.Classes,
  uAvroShield;

const
  DemoPassword = 'demo-avroshield-password';

  { Python json.dumps output (spaces after ':' / ',') - the Delphi serializer
    emits compact JSON, so both sides are compared whitespace-stripped. }
  ExpectedJson =
    '{"Metadata": {"encoding": "UTF-8", "version": 1, "name": "TestLayout"}, '
    + '"FullFormReplacements": {"a": "abc", "b": "def", "k": "'
    + Chr($09AC) + Chr($09BE) + Chr($0982) + Chr($09B2) + Chr($09BE)  { bangla }
    + '"}, "Nested": {"arr": [1, 2.5, true, null, "'
    + Chr($09AC) + Chr($09BE) + Chr($0982) + Chr($09B2) + Chr($09BE)
    + '"]}, "Ints": [-5, 0, 123456789012345678], "Empty": {}}';

var
  Fails: Integer;
  Tampered: TBytes;
  Dummy: string;
  Bc: TBytes;
  Node, Deobf: TAvroNode;
  Json: string;

function StripWS(const S: string): string;
var
  I: Integer;
begin
  Result := '';
  for I := 1 to Length(S) do
    if (S[I] <> ' ') and (S[I] <> #9) and (S[I] <> #10) and (S[I] <> #13) then
      Result := Result + S[I];
end;

procedure Check(const AName: string; ACond: Boolean; const ADetail: string = '');
begin
  if ACond then
    WriteLn('PASS ' + AName)
  else
  begin
    WriteLn('FAIL ' + AName);
    if ADetail <> '' then
      WriteLn('  ' + ADetail);
    Inc(Fails);
  end;
end;

function ReadAll(const AFileName: string): TBytes;
var
  FS: TFileStream;
begin
  Result := nil;
  if not FileExists(AFileName) then
    Exit;
  FS := TFileStream.Create(AFileName, fmOpenRead or fmShareDenyNone);
  try
    SetLength(Result, FS.Size);
    if FS.Size > 0 then
      FS.Read(Result[0], FS.Size);
  finally
    FS.Free;
  end;
end;

{ Loads the container and compares the deobfuscated JSON to ExpectedJson. }
procedure CheckContainer(const AName, AFile: string; AUseBind: Boolean;
  const APassword: string; AExpectOk: Boolean; AExpectResult: TAvroShieldResult);
var
  Json: string;
  R: TAvroShieldResult;
begin
  R := AvroShieldLoadFromFile(AFile, APassword, Json, AUseBind);
  if AExpectOk then
  begin
    Check(AName, R = asrOk,
      'result=' + IntToStr(Ord(R)) + ' (expected asrOk)');
    if R = asrOk then
      Check(AName + ' JSON', StripWS(Json) = StripWS(ExpectedJson),
        'json mismatch: ' + Json);
  end
  else
    Check(AName, R = AExpectResult,
      'result=' + IntToStr(Ord(R)) + ' (expected ' +
      IntToStr(Ord(AExpectResult)) + ')');
end;

begin
  Fails := 0;

  WriteLn('=== bytecode parse + deobfuscate ===');
  begin
    Bc := ReadAll('kat_sample.bytecode');
    Check('bytecode read', Length(Bc) > 0, 'cannot read kat_sample.bytecode');
    if Length(Bc) > 0 then
    begin
      Node := nil;
      Deobf := nil;
      if not AvroShieldParseBytecode(Bc, Node) then
        Check('bytecode parse', False, 'parse failed')
      else
      begin
        Check('bytecode parse', True);
        if AvroShieldDeobfuscate(Node, Deobf) then
        begin
          Json := AvroShieldNodeToJSON(Deobf);
          Check('bytecode deobfuscate+JSON',
            StripWS(Json) = StripWS(ExpectedJson), 'json mismatch: ' + Json);
          Deobf.Free;
        end
        else
          Check('bytecode deobfuscate', False, 'deobfuscate failed');
        Node.Free;
      end;
    end;
  end;

  WriteLn('=== portable container (password only, flags 0x09) ===');
  CheckContainer('portable load', 'kat_portable.AvroEnco', False,
    DemoPassword, True, asrOk);
  { No machine-bind flag -> loads even when the caller asks for binding. }
  CheckContainer('portable with bind on', 'kat_portable.AvroEnco', True,
    DemoPassword, True, asrOk);

  WriteLn('=== machine-bound container (flags 0x0F) ===');
  CheckContainer('bound load (this machine)', 'kat_bound.AvroEnco', True,
    DemoPassword, True, asrOk);
  CheckContainer('bound with bind off', 'kat_bound.AvroEnco', False,
    DemoPassword, False, asrMachineBindRequired);

  WriteLn('=== wrong password / tamper / format ===');
  CheckContainer('portable wrong pw', 'kat_portable.AvroEnco', False,
    'wrong-password', False, asrHmacFailed);
  CheckContainer('bound wrong pw', 'kat_bound.AvroEnco', True,
    'wrong-password', False, asrHmacFailed);

  { Tamper: flip one ciphertext byte (offset 100 is past the 58-byte header). }
  Tampered := ReadAll('kat_portable.AvroEnco');
  if Length(Tampered) = 0 then
    Check('tamper read file', False, 'cannot read kat_portable.AvroEnco')
  else
  begin
    Tampered[100] := Tampered[100] xor $FF;
    Check('tampered ciphertext', AvroShieldLoadFromBytes(Tampered,
      DemoPassword, Dummy, False) = asrHmacFailed,
      'expected asrHmacFailed');
  end;

  SetLength(Tampered, 200);
  FillChar(Tampered[0], 200, Ord('G'));
  Check('bad magic', AvroShieldLoadFromBytes(Tampered,
    DemoPassword, Dummy, False) = asrBadMagic, 'expected asrBadMagic');

  SetLength(Tampered, 40);
  Check('truncated file', AvroShieldLoadFromBytes(Tampered,
    DemoPassword, Dummy, False) = asrFileTooShort, 'expected asrFileTooShort');

  if Fails = 0 then
    WriteLn('ALL AVROSHIELD KATs PASSED')
  else
    WriteLn(IntToStr(Fails) + ' KAT(s) FAILED');

  if Fails > 0 then
    Halt(1);
end.
